# docker-compose.yml for Primary (OMITTED)

services:
  postgresql-primary:
    image: ${POSTGRES_IMAGE_REPOSITORY}:${POSTGRES_IMAGE_TAG}
    container_name: postgresql-primary
    hostname: postgres-primary
    network_mode: "host"
    restart: unless-stopped                                                       # Runs the container using the host machine’s network. Primary database in a different machine than Replica
    env_file:
      - .env
    environment:
      # Repmgr and replication settings
      - REPMGR_NODE_ID=${REPMGR_NODE_ID_PRIMARY}
      - REPMGR_NODE_NAME=${REPMGR_NODE_NAME_PRIMARY}
      - REPMGR_NODE_NETWORK_NAME=${REPMGR_NODE_NETWORK_NAME_PRIMARY}
      - REPMGR_PARTNER_NODES=${REPMGR_PARTNER_NODES} 
      - REPMGR_PRIMARY_HOST=${REPMGR_PRIMARY_HOST}
      - REPMGR_USERNAME=${REPMGR_USERNAME}
      - REPMGR_PASSWORD=${REPMGR_PASSWORD}
      - REPMGR_DATABASE=${REPMGR_DATABASE}

      # PostgreSQL credentials and database settings
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}

      # SSL configuration (ensure certificates are in the mounted cert folder)
      - POSTGRESQL_ENABLE_SSL=yes
      - POSTGRESQL_SSL_CERT_FILE=/opt/bitnami/postgresql/certs/server-primary.crt
      - POSTGRESQL_SSL_KEY_FILE=/opt/bitnami/postgresql/certs/server-primary.key
      - POSTGRESQL_SSL_CA_FILE=/opt/bitnami/postgresql/certs/ca.crt 
    volumes:
      - /mnt/pgdata:/bitnami/postgresql
      - ${INSTALL_PATH}/postgres-cluster/ssl:/opt/bitnami/postgresql/certs
      - ${INSTALL_PATH}/postgres-cluster/conf.d:/opt/bitnami/postgresql/conf.d
      - ${INSTALL_PATH}/postgres-cluster/postgresql.conf:/bitnami/postgresql/conf/postgresql.conf