version: '3.8'

services:
  mongo-1:
    container_name: 'mongo-1-container'
    image: 'mongo:6.0.20' #Running Mongo 6.X image
    command: ["--replSet", "rs0", "--bind_ip", "localhost,ls-spapr4cdb01.hluz.ess.local", "--port", "27017", "--keyFile", "/shared/keyfile.key"] #Starts as part of a replica set and listens for connections from other nodes
    network_mode: host
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}" #.env file
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}" #.env file
    volumes:
      - 'mongo1data:/data/db' #Default directory to store data
      - 'mongo1config:/data/configdb' #Used to store metadata
      - '/home/dedalus/data:/shared' #Shared volume to store keyfile and Init Script
    env_file:
      - .env

volumes:
  mongo1data:
  mongo1config: